import { access } from "node:fs/promises";
import path from "node:path";

const required = [
  "README.md",
  "AGENTS.md",
  "CLAUDE.md",
  "CONVENTIONS.md",
  "doctrine/AUTOMATON.md",
  "doctrine/GUARDRAILS.md",
  "doctrine/LANES.md",
  "doctrine/SCORING.md",
  "docs/operating-model.md",
  "docs/run-catalog.md",
  "docs/backlog.md",
  "docs/sourcey.config.ts",
  "docs/introduction.md",
  "docs/proving-ground.md",
  "docs/evolution.md",
  "docs/operating-model.md",
  "docs/flows.md",
  "docs/skill-upstream.md",
  "docs/operations.md",
  "state/priorities.md",
  "state/capabilities.md",
  "state/verification-profiles.json",
  "state/targets/nilstate-automaton.md",
  "state/targets/nilstate-runx.md",
  "history/README.md",
  "reflections/README.md",
  "site/package.json",
  "site/astro.config.mjs",
  "site/src/lib/content.js",
  "site/src/layouts/BaseLayout.astro",
  "site/src/pages/index.astro",
  "site/src/pages/priorities.astro",
  "site/src/pages/history.astro",
  "site/src/pages/capabilities.astro",
  "site/src/pages/reflections.astro",
  "site/src/pages/targets/index.astro",
  "site/src/pages/targets/[slug].astro",
  "schemas/skill-upstream-artifacts.schema.json",
  "schemas/skill-upstream-state.schema.json",
  "scripts/build-automaton-context.mjs",
  "scripts/build-automaton-context.test.mjs",
  "scripts/automaton-cycle.mjs",
  "scripts/automaton-cycle.test.mjs",
  "scripts/apply-automaton-promotions.mjs",
  "scripts/apply-automaton-promotions.test.mjs",
  "scripts/automaton-core.mjs",
  "scripts/automaton-core.test.mjs",
  "scripts/promote-automaton-state.mjs",
  "scripts/promote-automaton-state.test.mjs",
  "scripts/proving-ground.sh",
  "scripts/runx-agent-bridge.mjs",
  "scripts/sourcey-wrapper.sh",
  "scripts/prepare-skill-upstream.mjs",
  "scripts/validate-skill-upstream.mjs",
  "scripts/merge-watch.mjs",
  "scripts/prepare-issue-triage-decision.mjs",
  "scripts/run-issue-triage-plan.mjs",
  "scripts/post-issue-triage-comment.mjs",
  "scripts/run-issue-triage-workers.mjs",
  "scripts/publish-runx-pr.mjs",
  "scripts/publish-runx-pr.test.mjs",
  ".github/workflows/ci.yml",
  ".github/workflows/proving-ground.yml",
  ".github/workflows/docs-pages.yml",
  ".github/workflows/automaton-cycle.yml",
  ".github/workflows/sourcey-refresh.yml",
  ".github/workflows/issue-triage.yml",
  ".github/workflows/skill-lab.yml",
  ".github/workflows/skill-upstream.yml",
  ".github/workflows/merge-watch.yml",
];

for (const relativePath of required) {
  try {
    await access(path.resolve(relativePath));
  } catch {
    console.error(`missing required file: ${relativePath}`);
    process.exit(1);
  }
}

console.log("automaton check passed");
