import { access } from "node:fs/promises";
import path from "node:path";

const required = [
  "README.md",
  "AGENTS.md",
  "CLAUDE.md",
  "CONVENTIONS.md",
  "doctrine/ASTER.md",
  "doctrine/MISSION.md",
  "doctrine/EXAMPLES.md",
  "doctrine/CONDUCT.md",
  "doctrine/VOICE.md",
  "doctrine/EPISTEMOLOGY.md",
  "doctrine/AUTHORITY.md",
  "doctrine/EVOLUTION.md",
  "docs/operating-model.md",
  "docs/run-catalog.md",
  "docs/llm-training-spec.md",
  "docs/backlog.md",
  "docs/sourcey.config.ts",
  "docs/introduction.md",
  "docs/proving-ground.md",
  "docs/evolution.md",
  "docs/operating-model.md",
  "docs/flows.md",
  "docs/skill-upstream.md",
  "docs/operations.md",
  "state/priorities.md",
  "state/capabilities.md",
  "state/selection-policy.json",
  "state/aster-control.json",
  "state/verification-profiles.json",
  "spec/verification-profile.schema.json",
  "spec/workspace-change-plan-request.schema.json",
  "spec/issue-to-pr-request.schema.json",
  "spec/worker-request.schema.json",
  "spec/verification-report.schema.json",
  "spec/aster-control.schema.json",
  "spec/selector-training-row.schema.json",
  "state/targets/nilstate-aster.md",
  "state/targets/nilstate-runx.md",
  "history/README.md",
  "reflections/README.md",
  "site/package.json",
  "site/astro.config.mjs",
  "site/src/lib/content.js",
  "site/src/layouts/BaseLayout.astro",
  "site/src/pages/index.astro",
  "site/src/pages/doctrine/index.astro",
  "site/src/pages/doctrine/[slug].astro",
  "site/src/pages/priorities.astro",
  "site/src/pages/history.astro",
  "site/src/pages/capabilities.astro",
  "site/src/pages/reflections.astro",
  "site/src/pages/targets/index.astro",
  "site/src/pages/targets/[slug].astro",
  "schemas/skill-upstream-artifacts.schema.json",
  "schemas/skill-upstream-state.schema.json",
  "spec/aster-control.schema.json",
  "spec/selector-training-row.schema.json",
  "spec/issue-to-pr-request.schema.json",
  "spec/verification-profile.schema.json",
  "spec/verification-report.schema.json",
  "spec/worker-request.schema.json",
  "spec/workspace-change-plan-request.schema.json",
  "scripts/build-aster-context.mjs",
  "scripts/build-aster-context.test.mjs",
  "scripts/aster-cycle.mjs",
  "scripts/aster-cycle.test.mjs",
  "scripts/check-issue-triage-pr-policy.mjs",
  "scripts/check-issue-triage-pr-policy.test.mjs",
  "scripts/apply-aster-promotions.mjs",
  "scripts/apply-aster-promotions.test.mjs",
  "scripts/aster-core.mjs",
  "scripts/aster-core.test.mjs",
  "scripts/change-surface-governance.mjs",
  "scripts/change-surface-governance.test.mjs",
  "scripts/promote-aster-state.mjs",
  "scripts/promote-aster-state.test.mjs",
  "scripts/proving-ground.sh",
  "scripts/runx-agent-bridge.mjs",
  "scripts/prepare-skill-upstream.mjs",
  "scripts/validate-skill-upstream.mjs",
  "scripts/merge-watch.mjs",
  "scripts/enforce-generated-pr-policy.mjs",
  "scripts/prepare-issue-triage-decision.mjs",
  "scripts/evaluate-comment-quality.mjs",
  "scripts/evaluate-comment-quality.test.mjs",
  "scripts/evaluate-generated-pr.mjs",
  "scripts/evaluate-generated-pr.test.mjs",
  "scripts/generated-pr-policy.mjs",
  "scripts/generated-pr-policy.test.mjs",
  "scripts/issue-triage-markers.mjs",
  "scripts/issue-triage-replay-guard.mjs",
  "scripts/issue-triage-replay-guard.test.mjs",
  "scripts/operator-shakeout.mjs",
  "scripts/operator-shakeout.test.mjs",
  "scripts/run-issue-triage-plan.mjs",
  "scripts/run-governed-pr-lane.mjs",
  "scripts/run-governed-pr-lane.test.mjs",
  "scripts/post-issue-triage-comment.mjs",
  "scripts/post-issue-triage-pr-comment.mjs",
  "scripts/run-issue-triage-workers.mjs",
  "scripts/runx-control-schemas.mjs",
  "scripts/publish-runx-pr.mjs",
  "scripts/publish-runx-pr.test.mjs",
  "scripts/rollback-run.mjs",
  "scripts/rollback-run.test.mjs",
  "scripts/check-site-shared-surface.mjs",
  ".github/workflows/generated-pr-policy.yml",
  ".github/workflows/ci.yml",
  ".github/workflows/docs-pr.yml",
  ".github/workflows/fix-pr.yml",
  ".github/workflows/proving-ground.yml",
  ".github/workflows/rollback.yml",
  ".github/workflows/site-pages.yml",
  ".github/workflows/aster-cycle.yml",
  ".github/workflows/issue-triage.yml",
  ".github/workflows/skill-lab.yml",
  ".github/workflows/skill-upstream.yml",
  ".github/workflows/merge-watch.yml",
];

for (const relativePath of required) {
  try {
    await access(path.resolve(relativePath));
  } catch {
    console.error(`missing required file: ${relativePath}`);
    process.exit(1);
  }
}

const { loadVerificationProfileCatalogSync } = await import("./aster-v1-contracts.mjs");
loadVerificationProfileCatalogSync();
const { assertAsterSiteSharedSurface } = await import("./check-site-shared-surface.mjs");
await assertAsterSiteSharedSurface();

console.log("aster check passed");
